# Generated by Django 2.1.7 on 2019-05-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, default='')),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['track', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('track_number', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Album')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Track'),
        ),
    ]
