# Generated by Django 2.1.7 on 2019-04-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Record')),
            ],
            options={
                'ordering': ['record', 'start_time'],
            },
        ),
    ]
