# Generated by Django 2.1.7 on 2019-03-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_number', models.PositiveIntegerField(blank=True, null=True)),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assortment.Assortment')),
            ],
            options={
                'ordering': ['assortment', 'record_number'],
            },
        ),
    ]
